<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6eda9079-2c6b-43f7-b2cc-d19af047d7c9</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nebula.App.Shared\Nebula.App.Shared.csproj" />
    <ProjectReference Include="..\..\Corona\Corona\Corona.csproj" />
    <ProjectReference Include="..\..\Nebula.Agent\Nebula.Agent.csproj" />
    <ProjectReference Include="..\..\Nebula.Llama.Client\Nebula.Llama.Client.csproj" />
    <ProjectReference Include="..\..\Nebula.Mongo.Context\Nebula.Mongo.Context.csproj" />
    <ProjectReference Include="..\..\Nebula.Postgres.Context\Nebula.Postgres.Context.csproj" />
    <ProjectReference Include="..\..\Nebula.Runner\Nebula.Runner.csproj" />
    <ProjectReference Include="..\Nebula.App.Web.Client\Nebula.App.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

</Project>
