<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nebula.Llama.Client\Nebula.Llama.Client.csproj" />
    <ProjectReference Include="..\Nebula.Core\Nebula.Core.csproj" />
    <ProjectReference Include="..\Nebula.Services\Nebula.Services.csproj" />
    <ProjectReference Include="..\Nebula.Runner\Nebula.Runner.csproj" />
    <ProjectReference Include="..\Nebula.Mongo.Context\Nebula.Mongo.Context.csproj" />
    <ProjectReference Include="..\Nebula.Postgres.Context\Nebula.Postgres.Context.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
  </ItemGroup>

</Project>
