// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nebula.Postgres.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nebula.Postgres.Context.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20260615202920_add_ml_model_artifacts")]
    partial class add_ml_model_artifacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.CommandVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSafe")
                        .HasColumnType("boolean");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("command_verifications", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConversationContextId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("conversation_messages", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.ConversationState", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentGoal")
                        .HasColumnType("text");

                    b.Property<string>("CurrentPlan")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ConversationId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("conversation_states", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.FetchedPageCache", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HtmlHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Url");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("fetched_page_cache", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.KnowledgeExperiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandExecuted")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EvidenceHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("KnowledgeItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("StdErr")
                        .HasColumnType("text");

                    b.Property<string>("StdOut")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("TestCode")
                        .HasColumnType("text");

                    b.Property<string>("VerificationKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeItemId");

                    b.ToTable("knowledge_experiments", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.KnowledgeFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Fact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KnowledgeItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeItemId");

                    b.HasIndex("SourceUrl");

                    b.ToTable("knowledge_facts", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.KnowledgeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ClassificationConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FinalScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedCommand")
                        .HasColumnType("text");

                    b.Property<string>("OS")
                        .HasColumnType("text");

                    b.Property<double>("SafetyScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Shell")
                        .HasColumnType("text");

                    b.Property<double>("SourceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("VerificationScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("FinalScore");

                    b.HasIndex("Topic");

                    b.ToTable("knowledge_items", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.KnowledgeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExtractedContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KnowledgeItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TrustScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeItemId");

                    b.HasIndex("Url");

                    b.ToTable("knowledge_sources", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.MlModelArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("F1Score")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("ModelData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SchemaJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("TrainingDatasetHash")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("ml_model_artifacts", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.StoredCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CommandId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Executed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ExecutionResult")
                        .HasColumnType("text");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OsType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Executed");

                    b.HasIndex("OsType");

                    b.HasIndex("RequestId");

                    b.ToTable("commands", (string)null);
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.CommandVerification", b =>
                {
                    b.HasOne("Nebula.Postgres.Context.Entities.StoredCommand", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.KnowledgeExperiment", b =>
                {
                    b.HasOne("Nebula.Postgres.Context.Entities.KnowledgeItem", "KnowledgeItem")
                        .WithMany("Experiments")
                        .HasForeignKey("KnowledgeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeItem");
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.KnowledgeFact", b =>
                {
                    b.HasOne("Nebula.Postgres.Context.Entities.KnowledgeItem", "KnowledgeItem")
                        .WithMany("Facts")
                        .HasForeignKey("KnowledgeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeItem");
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.KnowledgeSource", b =>
                {
                    b.HasOne("Nebula.Postgres.Context.Entities.KnowledgeItem", "KnowledgeItem")
                        .WithMany("Sources")
                        .HasForeignKey("KnowledgeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeItem");
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.StoredCommand", b =>
                {
                    b.HasOne("Nebula.Postgres.Context.Entities.Request", "Request")
                        .WithMany("Commands")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.KnowledgeItem", b =>
                {
                    b.Navigation("Experiments");

                    b.Navigation("Facts");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Nebula.Postgres.Context.Entities.Request", b =>
                {
                    b.Navigation("Commands");
                });
#pragma warning restore 612, 618
        }
    }
}
